### ISSUE TITLE
Hardcoded path to /data when importing into Lidarr?

### ISSUE THREAD

**Issue by mattgoldspink** [mrusse/soularr#1]
Firstly thanks for this! Its awesome!
I tried it but it failed on the Lidarr import - it was looking for everything in /data
I assume it should be using the download path from Slskd that was configured?

**Comment by mrusse** [comment]
Sorry about that!! I totally forgot about that path and had left it hardcoded. I have fixed it with the latest commit. There is now a new option in the config under "Lidarr" called "download_dir". In Lidarr will need to mount the same path you are using in Slskd for your download directory and add that in the config. For example I have mine mounted in lidarr undar "/data". 

Let me know if you get it working.

**Comment by mattgoldspink** [comment]
Thanks! It's all working now! Appreciate it!
