### ISSUE TITLE
Small issue, docker compose PUID/GID is ignored and soularr.py is run as root, but user: xxxx:yyyy fixes it

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#14]
I kept seeing the soularr.py process run as root, which was not my intent given the PUID/GID entries in the environment section of the docker compose.  But adding a user entry such as "user: 1000:1000" under the soularr section of the docker compose fixes the issue. In addition to seeing the user id change in the running process, I confirmed the user change in the before/after cases by ssh'ing into the docker container, and doing a whoami.
As far as how to fix going forward on the git, I see 2 ways.  Either make changes to soularr.py so that you're actually importing/using the PUID/GID environment variables (I don't know how that works 100%).  Or maybe just change the docker compose file example to not use PUID/GID and instead use "user: xxxx:yyyy" instead, where xxxx is the user_id, and yyyy is the user_group.

**Comment by mrusse** [comment]
I have updated the [docker compose](https://github.com/mrusse/soularr/blob/main/docker-compose.yml) with `user: "${PUID}:${PGID}"`

Take a look and let me know if this fixes your issue. Thanks.

**Comment by yroyathon** [comment]
That's no good, docker gives these warnings about that...  
WARN[0000] The "PUID" variable is not set. Defaulting to a blank string.
WARN[0000] The "PGID" variable is not set. Defaulting to a blank string.

You could just drop the PUID/PGID in the environment: section, and then make it clear to people using standard nomenclature that they need to enter in their own PUID/PGID on the user: section.  But that it won't work as-is until actual numbers are entered for PUID/PGID.

**Comment by mrusse** [comment]
Ok, I thought that it would pull from the env vars but I guess not. Will just hardcode it as 1000:1000 for now and add a disclaimer that it can be set to whatever the user prefers.
