### ISSUE TITLE
Lock file remains if docker container doesn't exit gracefully

### ISSUE THREAD

**Issue by aurvandel** [mrusse/soularr#16]
Performing a docker compose down command on the container while the script is running doesn't trigger any type of code to delete the lock file. This causes the script to run but never import anything and just report that the instance is already running and waits the configured amount of seconds after you start the container again because the lock still exists. Probably just need to listen for interrupts in order to avoid missing the code to delete the lock file.

**Comment by mrusse** [comment]
@kappa118 Any ideas for this? At least for Docker the locking file seems redudent now since shell script itself checks if the script is running before running the python script. Maybe we could only make a locking file if `is_docker()` is False. Unless there is a better solution.

**Comment by aurvandel** [comment]
Submitted a PR to fix this issue. #20

**Comment by mrusse** [comment]
Fixed with https://github.com/mrusse/soularr/pull/20. Thank you.
