### ISSUE TITLE
Container crashed processing an album where track #1 downloaded successfully, rest of tracks completed-errored in soulseek

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#18]
At least that's my guess as to why the container crashed.  That was one noteworthy thing about this album that it failed on.

Waiting for downloads... monitor at: http://host.docker.internal:5030/soulseek/downloads
FAILED: Username: shaky-leg Directory: f:\soulseek\bruce peninsula\2009 - a mountain is a mouth
Traceback (most recent call last):
  File "/app/soularr.py", line 466, in <module>
    failed = grab_most_wanted(wanted_records)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 312, in grab_most_wanted
    cancel_and_delete(artist_folder['dir'], artist_folder['username'], directory["files"])
  File "/app/soularr.py", line 85, in cancel_and_delete
    shutil.rmtree(delete_dir)
  File "/usr/local/lib/python3.11/shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.11/shutil.py", line 703, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.11/shutil.py", line 701, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '01 - Inside - Outside.flac'
 Fatal error! Exiting...
07/10/2024 17:05:06 - Waiting for 300 seconds before checking again...

**Comment by mrusse** [comment]
I think this could probably be a permissions error with Slskd. 

`PermissionError: [Errno 13] Permission denied: '01 - Inside - Outside.flac'` 

Soularr is trying to delete the errored files but does not have the permissions it needs. Probably since Slskd is the owner of the files. To troubleshoot try setting the Slskd container variable `SLSKD_UMASK` to `000`

**Comment by yroyathon** [comment]
After some reading I tried umask 002 instead of 000.  I believe that fixed this issue, but I'll keep an eye on things.  I was able to get to the end of the python script and have Lidarr import an album for the first time, after dozens of tries.

**Comment by mrusse** [comment]
Nice! Will close this issue since you were able to get it working.
