### ISSUE TITLE
Docker container for easy deployment

### ISSUE THREAD

**Issue by adrianipopescu** [mrusse/soularr#2]
Can you please make this a simple docker container we can just load up in our stack?

Bonus points if you can share a sample docker-compose file for newbies like me.

**Comment by mrusse** [comment]
I have had a few requests for this and am taking time this weekend to try and set it up. Will report back on this issue.

**Comment by Skaronator** [comment]
Pleass consider using GitHub Container Registry instead of Docker Hub due to the annoying pull Limit in Docker Hub :)

**Comment by mrusse** [comment]
[Just made some changes for docker. ](https://github.com/mrusse/soularr/commit/4e99f3e185cfeaaaca67dd86bdc3dc4188599303)


Will update readme in a bit but for anyone who sees this before I do it is up on dockerhub:

https://hub.docker.com/r/mrusse08/soularr

Give it a test. You need to mount the folder that contains your config file to "/data" and also mount your slskd dl dir to whatever you want and put the directory you mounted it to in the config under Slskd -> "download_dir"

Also you can supply an environment var "SCRIPT_INTERVAL" which is how often the script is run in seconds. Default is 5 mins (300 seconds).

Also @Skaronator I will look into GitHub Container Registry but I know a lot of things search for apps in dockerhub (like Unraid).

**Comment by mrusse** [comment]
Readme has been updated with detailed docker instructions. Going to close this. Feel free to open more issues if you have specific problems with docker.
