### ISSUE TITLE
Feature request, intermittent Lidarr import, versus Lidarr import at end of all downloads

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#21]
Maybe this is just because I'm new at using this or because I have lots of missing albums, but it would be nice to have Soularr have Lidarr import albums after each download (or after every X downloads).  I tried using the setting grab_full_wanted_list = False, but after a while Soularr cannot find the first page of wanted albums (as was discussed in another issue I believe), and does nothing.  We are still discovering some bugs here and there that cause failures, so with long runtimes of just downloading that end in failure, there is no import done at all.  Also bugs aside, things happen and Soularr can get interrupted.  And as of this point, I don't believe that interrupted work is resumed.  That might be a separate loftier feature request (resume work of previously stopped run).  But for now, I'd be very happy with Lidarr imports after each download or after X downloads.

**Comment by yroyathon** [comment]
It looks like there are new changes coming to search_type...namely 'incrementing_wanted_page' .  I think maybe this would do what I wanted.  I could set Soularr to that, and for each run it would process a single page of wanted albums.  But for each successive run, it would increment the page number?  If I understand this feature-to-be-added, then I could do without the feature request I described above.

**Comment by AdamWHY2K** [comment]
you're understanding the new incrementing search correctly, and i think it should accomplish what you desire.

> after a while Soularr cannot find the first page of wanted albums (as was discussed in another issue I believe), and does nothing

yeah, the `remove_wanted_on_failure` option should be enabled to prevent this from happening, but this will mean lidarr won't re-search for failed items until you remonitor them.

**Comment by yroyathon** [comment]
Also super, I can't wait for the new search_type feature.

**Comment by mrusse** [comment]
The unmonitor feature is a setting. All you have to do is disable it. Also I am testing the search_type feature and will put out an update later today. Will close this for now but feel free to open specific issues about the search_type feature once you are able to test it.
