### ISSUE TITLE
Bug with the new page logic

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#22]
Traceback (most recent call last):

  File "/app/soularr.py", line 483, in <module>

    page = get_current_page(current_page_file_path)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/soularr.py", line 463, in get_current_page

    file.write(default_page)

TypeError: write() argument must be str, not int

**Comment by mrusse** [comment]
Should be fixed with the latest commit. Sorry should have caught before. Do another update and let me know if it works now. Thanks.

**Comment by mrusse** [comment]
Somehow it looks like your current page file was empty. Just pushed a fix for this.

**Comment by yroyathon** [comment]
Seems fixed.  Thanks!
