### ISSUE TITLE
Make the defaults in config.ini non-destructive

### ISSUE THREAD

**Issue by mattgoldspink** [mrusse/soularr#25]
I just pulled and ran and then realized it was removing albums it couldn't find from my wanted list. Ideally defaults should not do things that are not easily reversible.

**Comment by mrusse** [comment]
The albums will still be on the wanted list under unmonitored. Filter by unmonitored and you will see the albums. The setting is very easy to change.

**Comment by mrusse** [comment]
Did end up changing the defaults https://github.com/mrusse/soularr/commit/3531ef42b92e256cade0a3be26825c8190be0543

Now they are:
```ini
search_type = incrementing_page
remove_wanted_on_failure = False
```
