### ISSUE TITLE
shutil move, folder and artist name sanitized, destination already exists

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#28]
I'm not totally sure what happened.  Maybe it's related to the new sanitized code.  I'm also not sure how First Aid Kit - Stay Gold was grabbed 3 different times.... weird, it looks like a single/different track was downloaded from 3 different users, which itself seems bad. In Lidarr I can see that it's a single with 2 tracks, both with the same name, ie 01 Stay Gold and 02 Stay Gold are the track names in the single Stay Gold.  Very weird.  I think for simplicity I will just unmonitor this single.  But I can't explain how the separate searches came to be.

Log output
Downloads added: 
Username: Bueno Directory: Music\Organised Music\First Aid Kit\Turning Onto You
Username: mixxit Directory: Music\First Aid Kit\Stay Gold
Username: gullianvdwalt Directory: Artists\First Aid Kit\Extended Play's & Singles\Come Give Me Love (Single) [2020]
Username: gullianvdwalt Directory: Artists\First Aid Kit\The Boys of Summer (Single) (320) [2022]
Username: reverendwrong1 Directory: @@pdrxc\MUSIC\First Aid Kit\Stay Gold
Username: salvaam Directory: @@wnela\Music\First Aid Kit\Postcard
Username: CurlyRabbet Directory: @@bhhrm\Artists\First Aid Kit
Username: hideNseek Directory: r:\creation\2000 - wichita\webb319s first aid kit - the lion's roar
Username: honstune Directory: @@vwzxb\1. Music\JACK WHITE - Third Man Records Collection\First Aid Kit - Universal Soldier (7 Vinyl) Third Man Records
Username: rosielebontennant97 Directory: @@ckhec\Music\Media.localized\Music\First Aid Kit\You Are The Problem Here
-------------------
Waiting for downloads... monitor at: http://host.docker.internal:5030/soulseek/downloads
All tracks finished downloading!
Traceback (most recent call last):
  File "/app/soularr.py", line 520, in <module>
    failed = grab_most_wanted(wanted_records)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 368, in grab_most_wanted
    shutil.move(folder,artist_name_sanitized)
  File "/usr/local/lib/python3.11/shutil.py", line 851, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'First Aid Kit/Stay Gold' already exists
 Fatal error! Exiting...

**Comment by mrusse** [comment]
Have noticed something like this happening with my downloads too. Pretty sure it's related to the new search types. Will dig into it some more when I have time.

Considering doing an overhaul on the search types logic.

Will keep you updated.
