### ISSUE TITLE
Soularr grabbing from the wrong album, when searching for a singles album with 1 track

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#29]
This may be related to issue #28 but I'm not sure, maybe this new issue creates the scenario that causes issue 28.

But for this issue, I noticed some new behavior (or may it had never come up before, I added a bunch of singles today to my Wanted list).  Looking for the single First Aid Kid - Cedar Lane, which contains 1 track, 01 Cedar Lane.  It found that track in an album of another name (Stay Gold).  But the user mixxit only has one track of Stay Gold, track 04 which is called 04 Cedar Lane.  So Soularr found that the folder matched correctly the desired number of tracks, ie 1 track.  But the folder name Stay Gold is not the name of the wanted single, Cedar Lane.

So there seems to be no matching of the single/album name with the user's folder name.  FYI this did not crash Soularr, once I saw this weird behavior I stopped the docker container.  

EDIT: It also saves the fetched track in the download directory under the directory name 'Stay Gold'.  So it was looking for 'Cedar Lane' but it saved it just as the user had it, 'Stay Gold'.  I think this causes more problems for Soullar.

Here's some info from the log:
Searching album: First Aid Kit Cedar Lane
Search returned 100 results
...
Found match from user: mixxit for 1 tracks!

This below was pasted from the Download in slskd:
mixxit
Music\First Aid Kit\Stay Gold
File	Progress	Size
4. Cedar Lane.mp3

**Comment by mrusse** [comment]
This is simply a wrong match on soularrs end. Do to the nature of soulseek track mating will never be perfect. This is mainly an issue for singles since it has no other tracks to verify against. Will close for now as there is not a perfect solution.
