### ISSUE TITLE
MusicBrainz Integration

### ISSUE THREAD

**Issue by adrianipopescu** [mrusse/soularr#3]
Any chance we could see a musicbrainz integration as well, just to cleanup the media files retrieved from slsk?

**Comment by kappa118** [comment]
I could be wrong, but Lidarr should be handling this for you. You may just need to update your Lidarr media management settings to match what you want the file / directory naming conventions to be.

**Comment by mrusse** [comment]
As kappa118 said, I probably will not do this since Lidarr already integrates with musicbrainz. You could always fork the project and make something like this though.
