### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data/.current_page.txt'

### ISSUE THREAD

**Issue by lazara007** [mrusse/soularr#30]
Hello,

I'm running in Docker.
Error I receive:
PermissionError: [Errno 13] Permission denied: '/data/.current_page.txt'

services:
  soularr:
    container_name: soularr
    environment:
      PGID: '1000'
      PUID: '1000'
      SCRIPT_INTERVAL: '300'
      TZ: Etc/UTC
    hostname: soularr
    image: mrusse08/soularr:latest
    networks:
      reverseproxy-nw: null
    restart: unless-stopped
    user: 1000:1000
    volumes:
    - /mnt/media/Music/Soulseek/complete:/downloads:rw
    - /config/soularr:/data:rw
version: '3'

root@arrs:/config/soularr# ls -l
total 8
-rw-r--r-- 1 root root 872 Oct 10 06:35 config.ini
-rw-r--r-- 1 root root 748 Oct 10 08:17 docker-compose.yml

Thank you.

**Comment by lazara007** [comment]
Folder permission was the issue with the data folder. Probem solved.

**Comment by ramonskie** [comment]
i had the same issue. i changed the user permissions but the problem still remained for some reason.
after deleting `app/data` and restarting the container the problem was solved.
i think it was due to open filesystems
