### ISSUE TITLE
Character set of your files

### ISSUE THREAD

**Issue by davemacrae** [mrusse/soularr#31]
HI,

I assume that you are developing your code under Windows rather that *nix given that your line endings on soularr.py are DOS based (although that seems to the only file with DOS endings). Not a huge problem but it's really screwed up the requirements.txt file. It seems to be using UTF-16LE character set.

![image](https://github.com/user-attachments/assets/ede4faa7-4feb-42ca-aaf2-0821f7039531)

Can you check this please?

**Comment by mrusse** [comment]
I have done dos2unix on a few files. Please try the newest update.
