### ISSUE TITLE
Set SCRIPT_INTERVAL to 86400 and it never ran again

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#35]
The docker container has been running for 3 days, it seems fine and healthy and no issues.  I just thought for a go-forward basis for checking for new missing music or the old missing music, once a day would be fine.  I'll probably just reduce the script interval and see if that helps avoid this bug.

Last log entry ended like so (spelling mistake):
All tracks finished downloading!
Solarr finished. Exiting...
12/10/2024 21:31:21 - Waiting for 86400 seconds before checking again...

**Comment by yroyathon** [comment]
I have since set the interval to 21600, and it's been working well.

**Comment by mrusse** [comment]
Closing for now. Cannot repeat the issue on my end.
