### ISSUE TITLE
Doesn't continue until all errored files are complete

### ISSUE THREAD

**Issue by kappa118** [mrusse/soularr#4]
First off, this is great! I started doing this exact same thing a few weeks ago, but this is definitely more polished.

I added an album and the first match had several file errors. The script seemed to detect this and add that user to the ignored users list, which I believe is correct. It then re-added a new match which successfully downloaded. After this, the script was stuck in a 'waiting for downloads to complete' state. I believe this is because the other user, whose downloads failed, not ALL of the tracks failed. Others were kept in a remotely queued state.

Once I went in an manually cancelled the rest of the files, the script immediately continued. I believe that if a user has failed downloads and that match is no longer going to be monitored, all files, even if not errored, should be removed from the watching.

Also, side note: any recommendations for Slskd settings would be great! I came to Slskd from soulseek and notice that it doesn't seem to be as performance. Maybe it's just me, but Slskd doesn't seem to do more than 1 download at a time, even from multiple users. I'm hoping it's just some configuration I'm missing, but any setup suggestions for poeple coming fresh to Slskd would be very helpful.

**Comment by mrusse** [comment]
This is a known limitation of the script right now that I will work on when I get some time. I Have previously tried to remove downloads from errored users and it was giving me a lot of issues. Im sure it is possible though and will get back to it soon. As for Slskd settings I'm not exactly sure. This is also my first time using Slskd but it seems to be behaving the same as the other clients I have used, and for me it does download multiple files from multiple users at the same time. I do see a setting for the number of download slots in the Slskd docs. Maybe take a look here: [https://github.com/slskd/slskd/blob/master/docs/config.md#limits-and-user-groups](https://github.com/slskd/slskd/blob/master/docs/config.md#limits-and-user-groups)

**Comment by mrusse** [comment]
Will keep this open to update on my progress with auto removing the errored files.

**Comment by mrusse** [comment]
Merged your fix! Closing this issue. Thanks again!
