### ISSUE TITLE
Using filters when searching

### ISSUE THREAD

**Issue by CrimsonFlash** [mrusse/soularr#40]
Sorry if I missed this, but I checked the docs and all open/closed issues and couldn't find anyone having my issue.

I want to pull two types of files; flac or mp3, but I only want mp3 if the bitrate is 320kbps or variable. Is there a way to add a filter when searching with a specific filetype?

I tried adding mbr:320 to the "allowed_filetypes = flac,mp3 mbr:320" but that doesn't seem to work.

Thanks!

**Comment by mrusse** [comment]
That is high up on the todo list but right now it doesnt check the bitrate only the filetype. Will leave this open until the feature is implemented.

**Comment by vfedetz** [comment]
I would also be interested in this feature.

**Comment by mrusse** [comment]
Been doing some work to add filters to the searching so you can specify what bitrate / samplerate / bitdepth you want the searches to match to. The allowed_filetypes search option will now take the order of the types into account and treat it as a list of most to least preferred types. You can also include the attribute info with the filetype if you want a specific quality of file. For example:

`allowed_filetypes = flac 24/192,flac 16/44.1,mp3 320`

This would first try to match to very high quality (24/192) flacs then it would try to match to CD quality (16/44.1) and then finally try 320kbps mp3 files. If you do not care about the specific quality you can still just put "flac" or "mp3" without the filetype.

A few things are subject to change after I get feedback from users. For example if you put flac 16/44.1 as your preferred type it will search for that specific sample rate and bitdepth and will not match with an album even if it has a higher quality. This is currently solved by simply putting your preferred types at the start of the list and then the generic type at the end. For example:

`allowed_filetypes = flac 24/192,flac 16/44.1,flac`

This will try the first two qualities of flacs and if there are no perfect matches it will just try to match with any flac ignoring the attributes. So if there was a result that was flac 24/96 it would be missed by the first two and picked up by the last one. Alternatively you can just add that format to your allowed_filetypes as well.

I have just pushed it to `mrusse08/soularr:dev` so please give it a try and let me know any feedback.

**Comment by mrusse** [comment]
Added this feature in these commits. https://github.com/mrusse/soularr/compare/9248e59044e0...b399c184eeda

It is now pushed to `mrusse08/soularr:latest` 

Closing this issue. Thank you for the feedback.
