### ISSUE TITLE
bolean error

### ISSUE THREAD

**Issue by bartek666666** [mrusse/soularr#44]
Sometimes when searching the script exits with error:

Starting Soularr! 14/11/2024 22:48:34
[DEBUG|connectionpool|L243] 2024-11-14T22:48:35+0100: Starting new HTTP connection (1): localhost:8686
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:8686 "GET /api/v1/wanted/missing?pageSize=1&sortKey=albums.title&sortDirection=ascending HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:8686 "GET /api/v1/wanted/missing?page=19&pageSize=1&sortKey=albums.title&sortDirection=ascending HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:8686 "GET /api/v1/album/519?includeAllArtistAlbums=False HTTP/11" 200 None
[INFO|soularr|L157] 2024-11-14T22:48:35+0100: Selected release for T.Love: Official, Poland, CD, Mediums: 1, Tracks: 15, ID: 8080
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:8686 "GET /api/v1/track?artistId=45&albumId=519&albumReleaseId=8080 HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:8686 "GET /api/v1/album/519?includeAllArtistAlbums=False HTTP/11" 200 None
[INFO|soularr|L280] 2024-11-14T22:48:35+0100: Searching album: T.Love I Hate Rock'n'Roll
[DEBUG|connectionpool|L243] 2024-11-14T22:48:35+0100: Starting new HTTP connection (1): localhost:5030
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:5030 "POST /api/v0/searches HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:35+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f?includeResponses=False HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:36+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f?includeResponses=False HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:37+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f?includeResponses=False HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:38+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f?includeResponses=False HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:39+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f?includeResponses=False HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:40+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f?includeResponses=False HTTP/11" 200 None
[DEBUG|connectionpool|L546] 2024-11-14T22:48:40+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f/responses HTTP/11" 200 None
[INFO|soularr|L191] 2024-11-14T22:48:40+0100: Search returned 0 results
[DEBUG|connectionpool|L546] 2024-11-14T22:48:40+0100: http://localhost:5030 "GET /api/v0/searches/32fc65dc-a2d2-11ef-b732-5db1e0a0670f/responses HTTP/11" 200 None
[ERROR|soularr|L597] 2024-11-14T22:48:40+0100: Traceback (most recent call last):
  File "/home/slskd/soularr/soularr.py", line 595, in <module>
    failed = grab_most_wanted(wanted_records)
  File "/home/slskd/soularr/soularr.py", line 283, in grab_most_wanted
    if not success and search_settings.getboolean('search_for_tracks', True):
  File "/usr/lib/python3.10/configparser.py", line 1308, in get
    return _impl(self._name, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 830, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 1168, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: Fasle

[ERROR|soularr|L598] 2024-11-14T22:48:40+0100: 
 Fatal error! Exiting...

also, Lidarr is not importing

**Comment by mrusse** [comment]
`ValueError: Not a boolean: Fasle` You have a typo in your config file. Fasle should be False. As for lidarr not importing make sure you have mounted you slskd download dir in lidarr if lidarr is running through docker. Then you need to put the directory that you mounted it to in your Soularr config undar [Lidarr]. If you still have issues please join the discord and I can help you debug your config further. Thanks.

**Comment by bartek666666** [comment]
ah, right, my bad, thanks
