### ISSUE TITLE
Soularr keeps moving slskd's "incomplete" directory into "failed imports" which causes slskd to fail

### ISSUE THREAD

**Issue by kandykarter** [mrusse/soularr#45]
It's basically as it says in the title. Every time an import fails, Soularr moves the "incomplete" folder out of the soulseek download folder and into the "failed_imports" folder. Slskd will not launch or function correctly without this folder.

Is there anything I can do?

The logs feel like they're normal, but I'm unsure why the folder's being moved rather than copied, or its contents being moved but the folder being left intact. 

> 2024-11-28 21:43:55
[INFO|soularr|L367] 2024-11-28T13:43:55-0800: All tracks finished downloading!
2024-11-28 21:44:00
[INFO|soularr|L436] 2024-11-28T13:44:00-0800: Starting Lidarr import for: incomplete ID: 530032
2024-11-28 21:44:02
[INFO|soularr|L451] 2024-11-28T13:44:02-0800: Downloaded Albums Scan Failed to import from: /downloads/00-slsk/incomplete
2024-11-28 21:44:02
[INFO|soularr|L477] 2024-11-28T13:44:02-0800: Failed import moved to: failed_imports/incomplete
2024-11-28 21:44:02
[INFO|soularr|L626] 2024-11-28T13:44:02-0800: Solarr finished. Exiting...

**Comment by mrusse** [comment]
You most likely just need to add the "complete" folder onto the end of the directory in your soularr config. Can you post your config just to be sure.

**Comment by kandykarter** [comment]
Well, in slskd's config, the directories are set as such: 
 directories:
   incomplete: /downloads/00-slsk/incomplete
   downloads:  /downloads/00-slsk

and in soularr, it's this: 

download_dir = /downloads/00-slsk

Is it just silly to not have a "complete" folder? I guess that'd be an easy enough fix.

**Comment by mrusse** [comment]
Yes you need to have a complete folder.

**Comment by NovaCyntax** [comment]
I'm having a similar issue and can't seem to get it working. 

Soularr docker compose mounts:
      - /home/nova/slskd/downloads:/downloads
      - /home/nova/soularr/config:/data

Slskd docker compose mounts:
      - /home/nova/slskd:/app
      - /mnt/md0/Media/Music:/music

Lidarr docker compose mounts:
      - /home/nova/slskd:/slskd
 
Soularr config.ini:
#Slskd download directory. Should have set it up when installing Slskd.
download_dir = /downloads/complete

Slskd config.yml:
directories:                                              
   incomplete: /app/downloads/incomplete
   downloads: /app/downloads/complete

I've been playing around with this for a day, so my current configuration has changed a lot from what I originally attempted it with, but I haven't managed to find the winning combination yet

**Comment by mrusse** [comment]
Maybe try including the complete folder in your mount:  /home/nova/slskd/downloads/complete:/downloads 

Then in soularr config: download_dir = /downloads

**Comment by NovaCyntax** [comment]
Unfortunately, that didn't fix the issue. Below are my updated configuration parameters:

Soularr docker compose mounts:
- /home/nova/slskd/downloads/complete:/downloads
- /home/nova/soularr/config:/data

Slskd docker compose mounts:
- /home/nova/slskd:/app
- /mnt/md0/Media/Music:/music

Lidarr docker compose mounts:
- /home/nova/slskd:/slskd

Soularr config.ini:
#Slskd download directory. Should have set it up when installing Slskd.
download_dir = /downloads

Slskd config.yml:
directories:
incomplete: /app/downloads/incomplete
downloads: /app/downloads/complete

**Comment by NovaCyntax** [comment]
As a follow up, is it normal for a significant amount of downloads to just not import? My downloads almost always go to "failed_imports", and then when I move them back to "complete", some of them import. This is the best I've managed to get it working, but it still requires a significant amount of manual intervention, surely I'm missing something

**Comment by NovaCyntax** [comment]
Workaround solution for anyone experiencing issues with downloads continually appearing in "failed_imports" -

Go to Lidarr -> Settings -> Download Clients and add a "Usenet Blackhole" download client. You do not need to be using Usenet or anything like that for this, I am only using Soularr. Then, configure it with the below options (both directories should be the "failed_imports" directory, which should be visible within Lidarr if you've correctly mounted the slskd directory). 

![Screenshot_20241202-161136](https://github.com/user-attachments/assets/5903bded-1993-445e-82dd-79081be53d12)

Lidarr will now attempt to import any files within this folder automatically. If an automatic match can't be made, you will have to manually import it (which usually involves 1-2 clicks). I will be looking into a way to generate notifications when a certain number of manual imports are waiting to be made, so that too many aren't piling up. This solution is working great for me so far, and is saving me a lot of headache.

Note: The "failed_imports" directory is periodically deleted once it's empty by soularr it seems, which will occasionally cause the Blackhole Download Client to be unavailable in Lidarr. Eventually, the "failed_imports" directory will be automatically recreated by Soularr, and Lidarr will passively recognize the Blackhole Download Client and begin to import its downloads.

**Comment by mrusse** [comment]
Glad you found something that worked but it is definitly over complicating things. 

Lidarr docker compose mounts:

    /home/nova/slskd:/slskd

Looking at your lidarr mounts it appears you are mounting the entire slskd folder. Are you then putting /slskd/downloads/complete as the Lidarr directory in the Soularr config. If not that is why your imports fail.

**Comment by NovaCyntax** [comment]
I would say 60-70% of my downloads are being imported correctly by Soularr, perhaps my music library is just leading to odd pulls. However, the remaining 30-40% collecting in "failed_imports" will eat up space quickly on my SSD (which is very limited), so using this is a convenient way for me to manually import them or remove them through Lidarr's interface. Does Soularr automatically remove files from the "failed_imports" file at any time? I would like to ideally let it run in the background and never have to check in with it.

**Comment by beerygaz** [comment]
Came here to try and a solution to this.  A large percentage of my downloads are also ending up in 'failed_imports' but I can't see anything wrong with the files/albums.
```
[INFO|soularr|L436] 2025-01-02T07:38:43+0200: All tracks finished downloading!
[INFO|soularr|L505] 2025-01-02T07:38:48+0200: Starting Lidarr import for: Bastille ID: 5373
[INFO|soularr|L505] 2025-01-02T07:38:48+0200: Starting Lidarr import for: Dean Martin ID: 5374
[INFO|soularr|L505] 2025-01-02T07:38:48+0200: Starting Lidarr import for: Bruce Hornsby ID: 5375
[INFO|soularr|L505] 2025-01-02T07:38:48+0200: Starting Lidarr import for: The Script ID: 5376
[INFO|soularr|L520] 2025-01-02T07:39:30+0200: Downloaded Albums Scan Importing 14 tracks from: /slskd/Bastille
[INFO|soularr|L520] 2025-01-02T07:39:30+0200: Downloaded Albums Scan Failed to import from: /slskd/Dean Martin
[INFO|soularr|L546] 2025-01-02T07:39:30+0200: Failed import moved to: failed_imports/Dean Martin
[INFO|soularr|L520] 2025-01-02T07:39:30+0200: Downloaded Albums Scan Importing 12 tracks from: /slskd/Bruce Hornsby
[INFO|soularr|L520] 2025-01-02T07:39:30+0200: Downloaded Albums Scan Failed to import from: /slskd/The Script
[INFO|soularr|L546] 2025-01-02T07:39:30+0200: Failed import moved to: failed_imports/The Script
[INFO|soularr|L703] 2025-01-02T07:39:30+0200: 6: releases failed while downloading and are still wanted.
```

I'm choosing to move my files as opposed to hardlink, and I'm moving between NAS drives, could this be a timeout issue moving larger FLAC files?
