### ISSUE TITLE
Soularr-Dashboard created.

### ISSUE THREAD

**Issue by EricH9958** [mrusse/soularr#51]
I wanted to be able to see the progress of the Soularr queue without having to ssh in and look at the logs.  
This is a webpage that reads the logs from Soularr and uses a scrolling log display to let me monitor the queue.  
I'm not a coder by any means so if anyone has any suggestions let me know. 

https://github.com/EricH9958/Soularr-Dashboard

**Comment by mrusse** [comment]
Looks great!! I will add it to the readme so people can take a look.

**Comment by EricH9958** [comment]
Thanks,  really appreciate your help getting Soularr running.  I got bored today so I thought I would try my hand at making this.  Lots of help from Claude AI.

**Comment by mrusse** [comment]
Closing with https://github.com/mrusse/soularr/commit/9248e59044e05ab8083b3065df8ddcab03232332
