### ISSUE TITLE
Soularr not waiting long enough before declaring an import failed?

### ISSUE THREAD

**Issue by MaximumFish** [mrusse/soularr#55]
I'm having a recurring issue where some imports are failing due to "access denied" errors in Lidarr, but it seems to me as though the error is due to the file no longer existing when Lidarr tries to delete it.

- Files are moved (copied) correctly into the destination directory.
- Lidarr then tries to delete the source files but gets access denied.
- The import fails at this point and the (correctly renamed) destination files are left floating. Manually importing from the artist page fixes it.
- Connecting to the Lidarr container's console and manually deleting the source files (now in failed_imports) works, so it doesn't appear to be an actual permissions issue but, fwiw, SLSKD_UMASK is set to 002 and both Lidarr and Slskd run under the same group.

I don't know how Soularr is determining when an import has failed, but my gut feeling is that it's moving things into the failed_imports directory before the import has had chance to actually complete. Does that seem feasible?

**Comment by MaximumFish** [comment]
Interesting. OK, I'll try that and report back, thanks.

**Comment by MaximumFish** [comment]
Unfortunately that didn't help. It still manages to import some albums just fine, but fails on others. It feels like the difference is the number of tracks but I don't have any concrete evidence or explanation of why that might be.

In my efforts to fix it I changed both slskd and soularr to run as the exact same user as lidarr (and chown'd all of the relevant files and directories to match) but somehow this has changed the problem entirely while making it no better or worse. Now, rather than downloading the same album over and over due to "failed imports", it now just doesn't see completed downloads at all and is doing the exact same thing. I tried upping the stalled_timeout but that just makes it wait a bit longer before adding the album again.

I've confirmed via the container's shell that it can see the downloads directory, and that it's running as the correct user, and obviously it can login to slskd or it wouldn't be able to add anything to the queue.

I'm at a loss but also feeling like I should give up as it's wasting a lot of bandwidth as-is. Thanks for your efforts though, and I'll keep watching the project with interest.

**Comment by mrusse** [comment]
Sorry you are having so many problems. Like I said though Lidarr is in charge of importing and is the only thing that can "fail" the import. Nothing you change in Soularr will change that, stalled_timeout does not change how long it waits before grabbing the album again. It is the maximum time that the script will wait for downloads to complete. Nothing to do with importing. Have you checked the lidarr debug logs to see why it is failing the import?

**Comment by MaximumFish** [comment]
I appreciate your efforts. I don't have debug logging turned on but the info logs say eg:

```
System.UnauthorizedAccessException: Access to the path '/data/apps/slskd/downloads/album/track 11.flac' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in ./Lidarr.Common/Disk/DiskTransferService.cs:line 299
   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile(TrackFile trackFile, Artist artist, List`1 tracks, String destinationFilePath, TransferMode mode) in ./Lidarr.Core/MediaFiles/TrackFileMovingService.cs:line 144
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeTrackFile(TrackFile trackFile, LocalTrack localTrack, Boolean copyOnly) in ./Lidarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 79
   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Lidarr.Core/MediaFiles/TrackImport/ImportApprovedTracks.cs:line 240
```

But currently it's not even trying to import anything as the script doesn't appear to even notice that downloads have finished anymore. I don't know what I did to make that happen! As for the stalled_timeout setting, I thought that would start a new grab if the one it was waiting for hadn't finished in the period specified? As in it would assume it had failed?

All that said though, I've managed to grab most of what was missing now so I can't really do much in the way of additional troubleshooting without adding new things to the queue, so we can probably just close this as a "me" problem and I'll set it back up again from scratch again when I next need to use it.

Meanwhile there's a feature request for this sort of thing as an official integration over on the Lidarr Github. It might be of interest to you? https://github.com/slskd/slskd/issues/1222

Thanks again for your help and have a good Christmas.
